import type { Metadata } from 'next';
import '../assets/css/globals.css';
import { PropsWithChildren } from 'react';
import { Provider } from '@lib/components';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

type Props = Readonly<PropsWithChildren>;

export default function RootLayout({ children }: Props) {
	return (
		<html
			lang='en'
			suppressHydrationWarning
		>
			<body>
				<Provider>{children}</Provider>
			</body>
		</html>
	);
}
