import '../assets/css/globals.css';

import type { Metadata } from 'next';
import { PropsWithChildren } from 'react';
import { Providers } from '@app/providers';
import { Toaster } from '@lib/components';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

type Props = Readonly<PropsWithChildren>;

export default function RootLayout({ children }: Props) {
	return (
		<html
			lang='en'
			suppressHydrationWarning
		>
			<body>
				<Providers>
					{children}
					<Toaster />
				</Providers>
			</body>
		</html>
	);
}
